# Generated by Django 5.0.4 on 2024-04-17 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[('USD', '$'), ('UZS', "so'm")], default='UZS', max_length=10)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='media/cours/courses/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/cours/specialities/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/cours/teacher')),
                ('age', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(to='cours.course')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.position')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='speciality',
            field=models.ManyToManyField(to='cours.speciality'),
        ),
    ]
