# Generated by Django 5.0.4 on 2024-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
    ]
